# Generated by Django 6.1.1 on 2026-09-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
