# Generated by Django 6.1.1 on 2026-09-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
