# Generated by Django 6.1.1 on 2026-09-29 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_options_and_more'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Renewals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewalname', models.CharField(max_length=255)),
                ('customerprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('reminderdate', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(max_length=50)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('createdbyuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='products.product')),
                ('updatedbyuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals_updated', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='renewals.renewalstatus')),
            ],
        ),
        migrations.CreateModel(
            name='RenewalArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_startdate', models.DateField()),
                ('previous_enddate', models.DateField()),
                ('previous_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closedat', models.DateTimeField(auto_now_add=True)),
                ('archived_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_archives', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('renewal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_entries', to='renewals.renewals')),
            ],
        ),
    ]
