# Generated by Django 6.1.1 on 2026-09-29 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_and_more'),
        ('products', '0001_initial'),
        ('renewals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewals',
            name='createdbyuser',
        ),
        migrations.RemoveField(
            model_name='renewals',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='renewals',
            name='product',
        ),
        migrations.RemoveField(
            model_name='renewals',
            name='status',
        ),
        migrations.RemoveField(
            model_name='renewals',
            name='updatedbyuser',
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewalname', models.CharField(max_length=255)),
                ('customerprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startdate', models.DateField()),
                ('next_renewal_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('custom', 'Custom')], max_length=20)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('createdbyuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renewals.renewalstatus')),
                ('updatedbyuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RenewalArchive',
        ),
        migrations.DeleteModel(
            name='Renewals',
        ),
    ]
