# Generated by Django 6.1.1 on 2026-09-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0002_remove_renewals_createdbyuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='renewal',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual'), ('custom', 'Custom')], max_length=20),
        ),
    ]
