# Generated by Django 6.1.1 on 2026-09-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_and_more'),
        ('products', '0001_initial'),
        ('renewals', '0003_renewal_count_alter_renewal_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='renewal',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='products.product'),
        ),
        migrations.CreateModel(
            name='RenewalArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewalname', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(default=1)),
                ('customerprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startdate', models.DateField()),
                ('next_renewal_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(max_length=20)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='renewals.renewalstatus')),
            ],
        ),
    ]
