# Generated by Django 6.1.1 on 2026-09-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_userprofile_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('productcode', models.CharField(blank=True, max_length=100, null=True)),
                ('productdescription', models.TextField(blank=True, null=True)),
                ('costprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.company')),
            ],
        ),
    ]
